#
# This is a Talligent Heat template for deploying OpenBook.
# Default user/pass for the OpenBook UI is: openbook / Tall!gent
# supports Juno, Kilo

heat_template_version: 2013-05-23

description: >
  Talligent Heat template for deploying a single node
  OpenBook instance.

parameter_groups:
- parameters:
  - keyname
  - flavor
  - image
  - private_net
  - public_net
  - sharefile_user
  - sharefile_pass

parameters:
  keyname:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image
  private_net:
    type: string
    description: Name of the private network for the compute server
    default: private
    constraints:
      - custom_constraint: neutron.network
  public_net:
    type: string
    description: Name of the public network for the compute server
    default: public
    constraints:
      - custom_constraint: neutron.network
  sharefile_user:
    type: string
    label: Sharefile Username
    description: Username for accessing Talligent Sharefile
  sharefile_pass:
    type: string
    label: Sharefile Password
    description: Password for accessing Talligent Sharefile
    hidden: true

resources:
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      count: 1
      timeout: 3600

  wait_handle:
    type: OS::Heat::WaitConditionHandle
  
  administrative_password:
    type: OS::Heat::RandomString
  
  external_access:
    type: OS::Neutron::SecurityGroup
    properties:
      name: openbook-group
      description: Enable access to OpenBook and SSH access
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8443
          port_range_max: 8443
  public_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }
      security_groups:
      - {get_resource: external_access}
  
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: public_port }

  server:
    type: OS::Nova::Server
    properties:
      name: openbook-01
      keyname: { get_param: keyname }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: public_port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            $admin_password: { get_attr: [administrative_password, value] }
            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
            $floating_ip: { get_attr: [ floating_ip, floating_ip_address ] }
            $sharefile_user: { get_param: sharefile_user }
            $sharefile_pass: { get_param: sharefile_pass }
          template: |
            #!/bin/bash -ex
            apt-get install software-properties-common
            apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
            add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu trusty main'
            apt-get update
            
            export DEBIAN_FRONTEND=noninteractive
            
            # configure/confirm the default root password during installation
            debconf-set-selections <<< 'mariadb-server-10.0 mysql-server/root_password password $admin_password'
            debconf-set-selections <<< 'mariadb-server-10.0 mysql-server/root_password_again password $admin_password'
            apt-get -y install mariadb-server
            
            cat << EOF >> /root/.my.cnf
            [mysql]
            user=root
            password=$admin_password
            EOF
            
            # mysql_secure_installation  # this asks several questions
            ## Apparently, we can do these queries manually, instead
            mysql -uroot -p$admin_password <<-EOF
            DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
            DELETE FROM mysql.user WHERE User='';
            DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
            FLUSH PRIVILEGES;
            EOF
            
            ### TOMCAT ###
            apt-get install -y tomcat7 mariadb-client-core-10.0 ntp unzip
            sed -i 's/^jdk.tls.disabledAlgorithms=SSLv3/#jdk.tls.disabledAlgorithms=SSLv3/' /etc/java-7-openjdk/security/java.policy
            sed -i 's/Xmx.*\ /Xmx2048m /g' /etc/default/tomcat7
            sed -i '/^JAVA_OPTS/ s/"$/ -Djsse.enableSNIExtension=false -Djava.security.egd=file:\/dev\/urandom"/g' /etc/default/tomcat7
            
            # Generate key
            keytool -genkey -keyalg RSA -alias tomcat \
            -dname "CN=talligent.net, O=Talligent, L=Austin, S=Texas, C=US" \
            -keystore /etc/tomcat7/keystore.jks \
            -storepass $admin_password \
            -validity 360 \
            -keysize 2048 \
            -keypass $admin_password
            
            # Enable 8443 for tomcat
            cat << EOF >> /tmp/tomcat-ssl.patch
            87d86
            <     <!--
            89a89,90
            >                keystoreFile="/etc/tomcat7/keystore.jks"
            >                keystorePass="$admin_password"
            91d91
            <     -->
            EOF
            
            patch /etc/tomcat7/server.xml /tmp/tomcat-ssl.patch
            
            rm -rf /var/lib/tomcat7/webapps/ROOT
            service tomcat7 stop
            
            # Download and install OpenBook
            ##wget "http://10.0.2.1:8080/v1/AUTH_7c5852425d864bcc9622967942f2fe56/test-container/Openbook.war" -P /tmp/
            #wget "http://4697a425bb8fd03f7b24-30f44d71994a2698d571e9be7d46544e.r90.cf1.rackcdn.com/Openbook.war" -P /tmp/
            #unzip -q /tmp/Openbook.war -d /var/lib/tomcat7/webapps/Openbook
            export TOKEN=$(curl -s -X POST "https://talligent.sharefile.com/oauth/token" \
                         -H "Content-Type: application/x-www-form-urlencoded" \
                         -d "grant_type=password&client_id=eC8y8eeoeunxzOizZq2oeknIVfA9Jyjg&client_secret=PehmEqzEgKuGm2XOZWXIOUY3GyrKcfSmNtwPptPwt0tWxihs&username=$sharefile_user&password=$sharefile_pass" | python -c 'import sys, json; print json.load(sys.stdin)["access_token"]')
            export ITEM=$(curl -s -k 'https://talligent.sf-api.com/sf/v3/Items/Search?query=Openbook*.zip' -H "Authorization: Bearer $TOKEN" | python -c 'import sys, json; print json.load(sys.stdin)["Results"][0]["ItemID"]')
            curl -s -k -L -o "/tmp/Openbook.zip" "https://talligent.sf-api.com/sf/v3/Items($ITEM)/Download" -H "Authorization: Bearer $TOKEN"
            unzip -q /tmp/Openbook.zip -d /tmp
            unzip -q /tmp/Openbook-*/Openbook.war -d /var/lib/tomcat7/webapps/Openbook
            
            mysql -uroot -p$admin_password < /var/lib/tomcat7/webapps/Openbook/WEB-INF/classes/db/MySQL/create_openbook_schemas.sql
            
            # Set the public url for OpenBook
            sed -ri 's/(ROOT_PROVIDER_PUBLIC_URL = https:\/\/).*/\1$floating_ip:8443/' /var/lib/tomcat7/webapps/Openbook/WEB-INF/classes/openbook.properties
            chown -R tomcat7.tomcat7 /var/lib/tomcat7/webapps/Openbook
            
            service tomcat7 start
            
            # Sleep a little bit to allow tomcat to finish initial liquibase run for OpenBook
            sleep 60
            
            # Set logo path to be relative so that it uses the https path
            mysql -uroot -p$admin_password <<-EOF
            UPDATE openbook.t_provider 
            SET personalization_settings = '{"logoFileUrl":"/Openbook/static/images/Talligent-logo_small.png"}';
            EOF
            
            wc_notify --data-binary '{"status": "SUCCESS"}'

outputs:
  OpenBook_admin:
    description: OpenBook administrative user
    value: openbook
  OpenBook_admin_password:
    description: OpenBook administrative user password
    value: Tall!g3nt
  OpenBook_URL:
    description: The URL to access the OpenBook UI
    value:
      str_replace:
        template: https://host_ip:8443/Openbook
        params:
          host_ip: { get_attr: [ floating_ip, floating_ip_address ] }

